# -*- coding: utf-8 -*-
"""Turn each member page from a dead end into the country's hub.

Run from the repo root:
    python tools/build_member_hubs.py                report only
    python tools/build_member_hubs.py --write        apply

WHAT WAS WRONG. Qatar's page linked to ../#/a/all, ../#/news and ../toolkit/, the generic product
roots. A reader arrived interested in Qatar and every way out discarded that. Nothing on the page
pointed at Qatar's 129 registered funders, Qatar's 28 news items or the five Qatar papers that
already exist. The country was the one axis every dataset shares and the country page was the one
surface that used none of it.

NO NEW PROSE. Every number, label, title and link target here is read out of shared/catalog.json,
which is itself generated from the datasets. Nothing is described, characterised or summarised. The
pages already carry more encyclopedia prose than a philanthropy register needs, and the answer to a
thin page is not more writing, it is the data the site already holds.

The block is written between markers and replaced wholesale on each run, so this is idempotent and
a hand edit inside the markers will be overwritten. Everything outside them, including the
council-member prose and the footer, is untouched.

ABSENCE IS STATED, NOT HIDDEN. Where a dataset holds nothing for a country the block says which of
the four things that is, using the catalog's own vocabulary. Bahrain has one reported flow of
$39,877 and no itemised rows: that is aggregate_only, a fact about what reaches the UN system, and
it reads differently from Kuwait having no toolkit paper, which is only that nobody has written one.
"""
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CAT = os.path.join(ROOT, "shared", "catalog.json")
WRITE = "--write" in sys.argv
START = "<!-- country-hub:start  generated by tools/build_member_hubs.py, do not hand-edit -->"
END = "<!-- country-hub:end -->"


def esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))


def usd(n):
    """Whole dollars with thousands separators. No rounding to a friendlier number: the figure is
    the figure, and $39,877 rounded to nothing is how Bahrain came to look like a gap."""
    return "${:,}".format(int(n))


def metric(value, label, href=None, note=None):
    inner = '<span class="ch-fig">%s</span><span class="ch-lab">%s</span>' % (esc(value), esc(label))
    if note:
        inner += '<span class="ch-note">%s</span>' % esc(note)
    if href:
        return '<a class="ch-metric" href="%s">%s</a>' % (esc(href), inner)
    return '<div class="ch-metric ch-metric--flat">%s</div>' % inner


def build(iso3, c, region_papers):
    cv = c["coverage"]
    reg_slug, tk_sec = c["register_slug"], c["toolkit_section"]
    out = [START]
    out.append('<section class="country-hub" aria-labelledby="ch-h-%s">' % iso3.lower())
    out.append('<h2 class="ch-h" id="ch-h-%s">%s in this register</h2>'
               % (iso3.lower(), esc(c["label"])))

    # ---- the four figures
    out.append('<div class="ch-metrics">')
    out.append(metric("{:,}".format(cv["register"]["count"]), "funders listed",
                      "../#/c/%s" % reg_slug))

    f = cv["flows"]
    if f["status"] == "covered":
        out.append(metric(usd(f["reported_usd"]), "reported outbound flow",
                          note="%s flows, %s itemised" % ("{:,}".format(f["reported_flows"]),
                                                          "{:,}".format(f["itemised_rows"]))))
    elif f["status"] == "aggregate_only":
        out.append(metric(usd(f["reported_usd"]), "reported outbound flow",
                          note="%s flow, no itemised records"
                               % "{:,}".format(f["reported_flows"])))
    else:
        out.append(metric("none", "reported outbound flow",
                          note="nothing reported to the UN system"))

    t = cv["toolkit"]
    if t["status"] == "covered":
        out.append(metric(str(t["count"]), "toolkit papers", "../toolkit/#/%s" % tk_sec))
    else:
        out.append(metric("none", "toolkit papers", note="not written yet"))

    n = cv["news"]
    if n["status"] == "covered":
        out.append(metric(str(n["count"]), "news items", "../#/news",
                          note="last %s days" % n["window_days"]))
    else:
        out.append(metric("none", "news items",
                          note="nothing in the last %s days" % n["window_days"]))
    out.append('</div>')

    # ---- the papers, by title, because a count is not a way in
    papers = c["papers"]
    if papers:
        out.append('<h3 class="ch-sub">Papers on %s</h3>' % esc(c["label"]))
        out.append('<ul class="ch-papers">')
        for p in papers:
            out.append('<li><a href="../toolkit/#/%s/%s">%s</a><span class="ch-min">%s min</span></li>'
                       % (esc(tk_sec), esc(p["slug"]), esc(p["title"]), esc(p["minutes"])))
        out.append('</ul>')
    if region_papers:
        out.append('<h3 class="ch-sub">Papers covering the GCC as a whole</h3>')
        out.append('<ul class="ch-papers">')
        for p in region_papers:
            out.append('<li><a href="../toolkit/#/gcc/%s">%s</a><span class="ch-min">%s min</span></li>'
                       % (esc(p["slug"]), esc(p["title"]), esc(p["minutes"])))
        out.append('</ul>')

    # ---- where the register's own rows sit inside this country
    areas = c["register_areas"]
    if areas and areas != [c["label"]]:
        out.append('<h3 class="ch-sub">Where those funders are recorded</h3>')
        out.append('<ul class="ch-areas">')
        for a in areas:
            out.append('<li>%s</li>' % esc(a))
        out.append('</ul>')

    out.append('</section>')
    out.append(END)
    return "\n".join(out)


def main():
    cat = json.load(io.open(CAT, encoding="utf-8"))
    region = cat.get("region_papers") or []
    by_slug = {c["member_slug"]: (iso3, c) for iso3, c in cat["countries"].items()
               if c.get("member_slug")}
    changed = []
    for slug, (iso3, c) in sorted(by_slug.items()):
        path = os.path.join(ROOT, "members", slug + ".html")
        if not os.path.exists(path):
            sys.exit("catalog names member_slug %r but %s does not exist" % (slug, path))
        src = io.open(path, encoding="utf-8").read()
        block = build(iso3, c, region)

        if START in src and END in src:
            new = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda m: block, src,
                         flags=re.S)
            where = "replaced"
        else:
            # after the council-member block, which is where the page stops talking about
            # geography and has room to start talking about giving
            anchor = '</div>\n</main>'
            if src.count(anchor) != 1:
                anchor = '</main>'
                if src.count(anchor) != 1:
                    sys.exit("%s: cannot find one unambiguous place to insert" % path)
            new = src.replace(anchor, block + "\n" + anchor)
            where = "inserted"

        n_papers = len(c["papers"])
        print("  %-14s %-9s %4d funders  %d papers  flows %-14s news %d"
              % (slug, where, c["coverage"]["register"]["count"], n_papers,
                 c["coverage"]["flows"]["status"], c["coverage"]["news"]["count"]))
        if new != src:
            changed.append((path, new))

    if not WRITE:
        print()
        print("%d page(s) would change. Re-run with --write to apply." % len(changed))
        return
    for path, new in changed:
        tmp = path + ".tmp"
        io.open(tmp, "w", encoding="utf-8", newline="").write(new)
        os.replace(tmp, path)
    print()
    print("written: %d page(s)" % len(changed))
    # prove the markers are balanced on every page, or a later run would nest blocks
    for slug in by_slug:
        s = io.open(os.path.join(ROOT, "members", slug + ".html"), encoding="utf-8").read()
        assert s.count(START) == 1 and s.count(END) == 1, "%s has unbalanced markers" % slug
    print("verified: one hub block per page, markers balanced")


if __name__ == "__main__":
    main()
