# -*- coding: utf-8 -*-
"""Make the register findable and shareable, without writing a word of new copy.

Run from the repo root:
    python tools/build_seo.py                report only
    python tools/build_seo.py --write        apply

WHAT WAS MISSING, measured before this ran. No sitemap.xml. No robots.txt. No canonical on any
page. Zero Open Graph tags anywhere, so sharing a link produced no title, no description and no
image on LinkedIn, in WhatsApp or anywhere else. Zero structured data. Seven of the thirteen
real URLs had no meta description. The register's own 1,862 organisations appear in 713 characters of
served HTML, on one URL, because the whole thing is a hash-routed application: a crawler that does
not run JavaScript sees a page with no organisation names on it at all.

WHAT IS NOT ATTEMPTED. Nothing here pretends the hash routes are pages. #/c/qatar cannot be in a
sitemap because it is not a URL a server can serve, and listing it would be a claim that is not
true. The thirteen real documents are listed and that is all.

WHERE THE WORDS COME FROM. Every title and description is either already in the page or assembled
from shared/catalog.json. The member pages had no description; theirs is now built from their own
figures, in the same way the country hub is, so the sentence is a reading of the data rather than
a piece of writing about the country.

THE MEMBER PAGES STOP BEING noindex. They carried it with no recorded reason, and while they held
237 to 353 words of general country prose that was the right call: thin, generic, and better
answered elsewhere. They now carry their register count, their reported outbound flow, their named
papers and where their funders sit, which exists nowhere else. The prose above it is left exactly
as it was.
"""
import io
import json
import os
import re
import sys
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://gccphilanthropy.org"
WRITE = "--write" in sys.argv
MARK_A = "<!-- seo:start  generated by tools/build_seo.py, do not hand-edit -->"
MARK_B = "<!-- seo:end -->"


def esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))


def read(p):
    return io.open(p, encoding="utf-8").read()


def title_of(src):
    m = re.search(r"<title>(.*?)</title>", src, re.S)
    return re.sub(r"\s+", " ", m.group(1)).strip() if m else ""


def desc_of(src):
    m = re.search(r'<meta\s+name="description"\s+content="([^"]*)"', src)
    return m.group(1).strip() if m else ""


def block(url, title, desc, extra_ld=None):
    """Canonical, Open Graph, Twitter and one JSON-LD graph, in one replaceable block."""
    out = [MARK_A,
           '<link rel="canonical" href="%s">' % esc(url),
           '<meta property="og:type" content="website">',
           '<meta property="og:site_name" content="Gulf Cooperation Council (GCC) Philanthropy">',
           '<meta property="og:url" content="%s">' % esc(url),
           '<meta property="og:title" content="%s">' % esc(title),
           '<meta property="og:description" content="%s">' % esc(desc),
           '<meta property="og:image" content="%s/gcc-emblem.svg">' % SITE,
           '<meta name="twitter:card" content="summary">',
           '<meta name="twitter:title" content="%s">' % esc(title),
           '<meta name="twitter:description" content="%s">' % esc(desc)]
    if extra_ld:
        out.append('<script type="application/ld+json">%s</script>'
                   % json.dumps(extra_ld, ensure_ascii=False, separators=(",", ":")))
    out.append(MARK_B)
    return "\n".join(out)


def apply_block(src, blk):
    if MARK_A in src and MARK_B in src:
        return re.sub(re.escape(MARK_A) + r".*?" + re.escape(MARK_B), lambda m: blk, src, flags=re.S)
    # immediately before </head>, so a page's own tags still win where they overlap
    if src.count("</head>") != 1:
        raise SystemExit("cannot find one </head>")
    return src.replace("</head>", blk + "\n</head>")


def ensure_desc(src, desc):
    """Add a description only where the page has none. An existing one is the author's."""
    if re.search(r'<meta\s+name="description"', src):
        return src, False
    return src.replace("</head>", '<meta name="description" content="%s">\n</head>'
                       % esc(desc)), True


def drop_noindex(src):
    new = re.sub(r'\s*<meta\s+name="robots"\s+content="noindex"\s*>', "", src)
    return new, new != src


def money(n):
    return "${:,}".format(int(n))


def main():
    cat = json.load(io.open(os.path.join(ROOT, "shared", "catalog.json"), encoding="utf-8"))
    reg = json.load(io.open(os.path.join(ROOT, "data.json"), encoding="utf-8"))
    pages = []                                   # (relpath, url, lastmod-source)

    # ---------------- the register itself
    p = "index.html"
    src = read(os.path.join(ROOT, p))
    t, d = title_of(src), desc_of(src)
    ld = {"@context": "https://schema.org", "@graph": [
        {"@type": "WebSite", "@id": SITE + "/#website", "url": SITE + "/", "name": t,
         "inLanguage": "en-GB",
         "potentialAction": {"@type": "SearchAction",
                             "target": {"@type": "EntryPoint",
                                        "urlTemplate": SITE + "/?search={search_term_string}"},
                             "query-input": "required name=search_term_string"}},
        {"@type": "Dataset", "@id": SITE + "/#register", "name": t, "description": d,
         "url": SITE + "/", "inLanguage": "en-GB",
         "creator": {"@type": "Person", "name": "Ali Al Mokdad"},
         "isAccessibleForFree": True,
         "variableMeasured": [k for k in reg["keys"]],
         "spatialCoverage": [{"@type": "Country", "name": c["label"]}
                             for c in cat["countries"].values()],
         "distribution": {"@type": "DataDownload", "encodingFormat": "application/json",
                          "contentUrl": SITE + "/data.json"}}]}
    pages.append((p, SITE + "/", src))
    yield_edits = [(p, apply_block(src, block(SITE + "/", t, d, ld)))]

    # ---------------- the toolkit
    p = "toolkit/index.html"
    src = read(os.path.join(ROOT, p))
    t, d = title_of(src), desc_of(src)
    url = SITE + "/toolkit/"
    notes = json.load(io.open(os.path.join(ROOT, "toolkit", "notes.json"), encoding="utf-8"))
    ld = {"@context": "https://schema.org", "@type": "CollectionPage", "url": url, "name": t,
          "description": d, "inLanguage": "en-GB",
          "isPartOf": {"@id": SITE + "/#website"},
          "dateModified": notes.get("compiled"),
          "about": [{"@type": "Country", "name": c["label"]} for c in cat["countries"].values()]}
    yield_edits.append((p, apply_block(src, block(url, t, d, ld))))
    pages.append((p, url, src))

    # ---------------- the member pages
    for iso3, c in sorted(cat["countries"].items(), key=lambda kv: kv[1]["label"]):
        slug = c["member_slug"]
        p = "members/%s.html" % slug
        full = os.path.join(ROOT, p)
        src = read(full)
        cv = c["coverage"]
        bits = ["%s funders recorded in %s" % ("{:,}".format(cv["register"]["count"]), c["label"])]
        f = cv["flows"]
        if f.get("reported_usd"):
            bits.append("reported outbound humanitarian flow of %s" % money(f["reported_usd"]))
        if cv["toolkit"]["count"]:
            bits.append("%d papers on its legal and regulatory framework" % cv["toolkit"]["count"])
        d = ", ".join(bits) + "."
        t = title_of(src)
        url = "%s/members/%s.html" % (SITE, slug)
        ld = {"@context": "https://schema.org", "@type": "WebPage", "url": url, "name": t,
              "description": d, "inLanguage": "en-GB",
              "isPartOf": {"@id": SITE + "/#website"},
              "about": {"@type": "Country", "name": c["label"],
                        "identifier": {"@type": "PropertyValue",
                                       "propertyID": "ISO 3166-1 alpha-3", "value": iso3}}}
        new = apply_block(src, block(url, t, d, ld))
        new, added = ensure_desc(new, d)
        new, lifted = drop_noindex(new)
        yield_edits.append((p, new))
        pages.append((p, url, src))
        print("  %-24s description %s, noindex %s"
              % (p, "added" if added else "kept", "lifted" if lifted else "not present"))

    # ---------------- the members index
    p = "members/index.html"
    src = read(os.path.join(ROOT, p))
    t = title_of(src)
    d = ("The six Gulf Cooperation Council member states, with the number of funders recorded "
         "in each: " + ", ".join("%s %s" % (c["label"], "{:,}".format(
             c["coverage"]["register"]["count"]))
             for c in sorted(cat["countries"].values(), key=lambda x: x["label"])) + ".")
    url = SITE + "/members/"
    ld = {"@context": "https://schema.org", "@type": "CollectionPage", "url": url, "name": t,
          "description": d, "inLanguage": "en-GB", "isPartOf": {"@id": SITE + "/#website"},
          "about": [{"@type": "Country", "name": c["label"]} for c in cat["countries"].values()]}
    new = apply_block(src, block(url, t, d, ld))
    new, added = ensure_desc(new, d)
    new, lifted = drop_noindex(new)
    yield_edits.append((p, new))
    pages.append((p, url, src))
    print("  %-24s description %s, noindex %s"
          % (p, "added" if added else "kept", "lifted" if lifted else "not present"))

    # ---------------- the four site-meta pages, which another session generates
    for name in ("privacy", "terms", "faq", "connect"):
        p = "%s/index.html" % name
        full = os.path.join(ROOT, p)
        if not os.path.exists(full):
            continue
        src = read(full)
        t, d = title_of(src), desc_of(src)
        url = "%s/%s/" % (SITE, name)
        ld = {"@context": "https://schema.org", "@type": "WebPage", "url": url, "name": t,
              "description": d, "inLanguage": "en-GB", "isPartOf": {"@id": SITE + "/#website"}}
        yield_edits.append((p, apply_block(src, block(url, t, d, ld))))
        pages.append((p, url, src))

    # ---------------- sitemap and robots
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    NS = "http://www.sitemaps.org/schemas/sitemap/0.9"
    sm = ['<?xml version="1.0" encoding="UTF-8"?>',
          '<urlset xmlns="%s">' % NS]
    for _, url, _ in pages:
        sm.append("  <url><loc>%s</loc><lastmod>%s</lastmod></url>" % (esc(url), stamp))
    sm.append("</urlset>")
    sitemap = "\n".join(sm) + "\n"

    robots = ("User-agent: *\n"
              "Allow: /\n"
              "Sitemap: %s/sitemap.xml\n" % SITE)

    print()
    print("  urls in the sitemap : %d" % len(pages))
    for _, u, _ in pages:
        print("     %s" % u)

    if not WRITE:
        print()
        print("nothing written. Re-run with --write to apply.")
        return

    for rel, new in yield_edits:
        full = os.path.join(ROOT, rel)
        tmp = full + ".tmp"
        io.open(tmp, "w", encoding="utf-8", newline="").write(new)
        os.replace(tmp, full)
    io.open(os.path.join(ROOT, "sitemap.xml"), "w", encoding="utf-8", newline="\n").write(sitemap)
    io.open(os.path.join(ROOT, "robots.txt"), "w", encoding="utf-8", newline="\n").write(robots)
    print()
    print("  written: %d page(s), sitemap.xml, robots.txt" % len(yield_edits))
    for rel, _ in yield_edits:
        s = read(os.path.join(ROOT, rel))
        assert s.count(MARK_A) == 1 and s.count(MARK_B) == 1, "%s markers unbalanced" % rel
        assert s.count('rel="canonical"') == 1, "%s has %d canonicals" % (
            rel, s.count('rel="canonical"'))
    print("  verified: one seo block and one canonical per page")


if __name__ == "__main__":
    main()
