# -*- coding: utf-8 -*-
"""
Builds /privacy/, /terms/, /faq/ and /connect/ from the SAME content module that produces the Word
edition of the three notices.

WHY IT IS GENERATED. These four pages carry legal statements. If the web copy and the Word copy are
written twice they will differ, and the difference will be discovered by the person the notice was
written to protect. So there is one source of words and two renderers, and the HTML is an output
rather than a document. The same reasoning, and the same arrangement, as shared/tokens.css against
the :root block in index.html.

DO NOT HAND-EDIT THE GENERATED PAGES. Edit the content module and run this again.

    py tools/build-legal.py <path-to-content.py> [repo-root]

The content module is the one used by the Word build, and EVERY string on the four pages comes out
of it. The connect form's own words live there too, in C.FORM, including the honeypot's label,
because the trap has to look like a real field to a bot and therefore needs a real one. No string
on these pages is typed into this file.
"""
import html
import os
import re
import sys
import importlib.util

SRC  = sys.argv[1] if len(sys.argv) > 1 else "content.py"
ROOT = sys.argv[2] if len(sys.argv) > 2 else os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

spec = importlib.util.spec_from_file_location("legalcontent", SRC)
C = importlib.util.module_from_spec(spec)
spec.loader.exec_module(C)

E = html.escape

# The product bar. These four pages are not products, so no entry is marked current: the page tab
# names the surface instead. The bar is here so a reader arriving from a search result has a way
# into the site rather than one link home.
PBAR = """<div class="pbar">
  <div class="wrap">
    <nav aria-label="Products">
      <a class="pbar-brand" href="../">GCC Philanthropy</a>
      <ul class="pbar-nav">
        <li><a href="../#/a/all">Atlas</a></li>
        <li><a href="../#/a/list">Register</a></li>
        <li><a href="../#/news">News &amp; Insights</a></li>
        <li><a href="../toolkit/">Toolkit</a></li>
        <li><a href="../members/">GCC Countries</a></li>
      </ul>
    </nav>
  </div>
</div>"""

def masthead(tab):
    return """<header class="top">
  <div class="container">
    <p class="brandline"><a class="home" href="../">Gulf Cooperation Council <span class="abbr">(GCC)</span> Philanthropy</a></p>
    <p class="kick">United Arab Emirates &middot; Saudi Arabia &middot; Qatar &middot; Kuwait &middot; Bahrain &middot; Oman</p>
  </div>
  <span class="pagetab" aria-hidden="true">%s</span>
</header>""" % E(tab)

FOOT_LINKS = [("../faq/", "FAQ", "faq"), ("../connect/", "Connect", "connect"),
              ("../terms/", "Terms of Use", "terms"), ("../privacy/", "Privacy Policy", "privacy")]

def footer(current):
    '''THE SITE SIGNATURE, the same three columns as every other page on the site.

    This used to emit a flat row of four links with the brand name beneath it and no ownership
    credit, which made these five the only pages that did not carry his name, while the seven
    country pages were the only ones that did not carry the links, and the toolkit carried
    neither. One shape now. The rules live in shared/chrome.css, which every page already loads.
    '''
    NL = chr(10)
    def link(slug, label):
        cur = ' aria-current="page"' if slug == current else ""
        return '      <li><a href="../%s/"%s>%s</a></li>' % (slug, cur, E(label))
    left = NL.join([link("faq", "FAQ"), link("connect", "Connect")])
    right = NL.join([link("terms", "Terms of Use"), link("privacy", "Privacy Policy")])
    return '''<footer class="sig">
  <div class="wrap">
    <nav class="sig-cols" aria-label="Site information">
    <ul class="sig-col sig-col-l">
%s
    </ul>
    <p><a class="sig-ava" href="https://www.linkedin.com/in/ali-al-mokdad/"
       target="_blank" rel="noopener noreferrer" aria-label="Ali Al Mokdad on LinkedIn"><img
       src="../ali.jpg" alt="" width="40" height="40" loading="lazy" decoding="async"></a><span
       class="sig-cred">Owned and managed by <a href="https://www.linkedin.com/in/ali-al-mokdad/"
       target="_blank" rel="noopener noreferrer">Ali Al Mokdad</a></span></p>
    <ul class="sig-col sig-col-r">
%s
    </ul>
    </nav>
  <p class="sig-rights">&copy; 2026 GCC Philanthropy&trade;. All rights reserved.</p>
</div></footer>''' % (left, right)


def head(title, desc, tab):
    return """<!doctype html>
<!-- GENERATED by tools/build-legal.py from the same content module as the Word edition.
     DO NOT HAND-EDIT: edit the content module and run the generator again, or the web copy and
     the Word copy will say different things about the same obligation. -->
<!-- ANTI_SLOP_BRIEF
  BOLD MOVE   One white sheet on the tinted ground, the toolkit's own construction, holding a
              document read top to bottom. No cards, no accordions, no hero. A legal notice is a
              document and it is presented as one.
  TYPE        Source Serif 4 for the prose, IBM Plex Mono for the section numbers and labels.
              WEIGHTS 400 AND 600 ONLY, never lighter: a notice set in a hairline reads as
              decoration rather than a statement anyone stands behind.
  COLOUR      shared/tokens.css only. Blueberry on section numbers, links and the send button.
              Masthead navy on titles. Orange stays reserved for the page tab.
  WORDS       EVERY WORD IS GENERATED from the reviewed content module, so the page and the Word
              edition cannot disagree. That includes the headings, the form's labels, its button,
              its human check, its honeypot label and its two result lines. Nothing is typed into
              the builder.
  VERIFIABLE  The version date and the register's counts come from the same source as the Word
              edition. Nothing on these pages is estimated or restated from memory.
-->
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%s | GCC Philanthropy</title>
<meta name="description" content="%s">
<meta name="color-scheme" content="light dark">
<link rel="icon" type="image/svg+xml" href="../gcc-emblem.svg">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="../shared/tokens.css">
<link rel="stylesheet" href="../shared/chrome.css">
<link rel="stylesheet" href="../shared/doc.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Serif+4:opsz,wght@8..60,400;8..60,600&family=IBM+Plex+Mono:wght@400;600&display=swap">
</head>
<body>
%s
%s
<main>
<div class="doc-wrap"><div class="container"><div class="sheet"><div class="doc">""" % (
        E(title), E(desc), PBAR, masthead(tab))

TAIL = """</div></div></div></div>
</main>
%s
</body>
</html>
"""

# Bare hosts in the transfer bullets and the address in the policy are the two things a reader
# reaches for. Linking them changes no word on the page.
HOST = re.compile(r"\b((?:[a-z0-9-]+\.)+(?:com|org|dev|eu|dk)(?:/[A-Za-z0-9/_.-]*)?)")
MAIL = re.compile(r"\b([a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,})\b")

def linkify(s):
    out = MAIL.sub(lambda m: '<a href="mailto:%s">%s</a>' % (m.group(1), m.group(1)), s)
    def h(m):
        u = m.group(1)
        if "@" in u or 'mailto:' in out[:m.start()][-20:]:
            return u
        return '<a href="https://%s" rel="noopener">%s</a>' % (u, u)
    parts, last = [], 0
    for m in re.finditer(r'<a [^>]*>.*?</a>', out):
        parts.append(HOST.sub(h, out[last:m.start()])); parts.append(m.group(0)); last = m.end()
    parts.append(HOST.sub(h, out[last:]))
    return "".join(parts)

def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")

def render(blocks):
    """content blocks -> html. Consecutive bullets and lettered items become one real list."""
    out, i = [], 0
    while i < len(blocks):
        b = blocks[i]; k = b[0]
        if k == "h2":
            out.append('<h2 id="s%s"><span class="n">%s</span>%s</h2>' % (b[1], E(b[1]), E(b[2])))
        elif k == "grp":
            out.append('<h2 class="grp" id="g-%s">%s</h2>' % (slug(b[1]), E(b[1])))
        elif k == "p":
            out.append("<p>%s</p>" % linkify(E(b[1])))
        elif k == "a":
            out.append("<p>%s</p>" % linkify(E(b[1])))
        elif k == "q":
            out.append("<h3>%s</h3>" % E(b[1]))
        elif k == "more":
            # a paragraph that is only a link. It exists so an answer can end in a word rather
            # than in a bare URL, and so the label and the target both live in the content module.
            out.append('<p class="more"><a href="%s">%s</a></p>' % (E(b[2]), E(b[1])))
        elif k == "lead":
            out.append('<p><span class="lead">%s</span>%s</p>' % (E(b[1]), linkify(E(b[2]))))
        elif k == "kv":
            out.append('<p class="kv"><span>%s</span> <b>%s</b></p>'
                       % (E(b[1]), linkify(E(b[2]))))
        elif k == "bul":
            items = []
            while i < len(blocks) and blocks[i][0] == "bul":
                items.append("<li>%s</li>" % linkify(E(blocks[i][1]))); i += 1
            out.append("<ul>%s</ul>" % "".join(items)); continue
        elif k == "let":
            items = []
            while i < len(blocks) and blocks[i][0] == "let":
                items.append("<li>%s</li>" % linkify(E(blocks[i][2]))); i += 1
            out.append("<ol>%s</ol>" % "".join(items)); continue
        else:
            raise SystemExit("unknown block kind %r" % (k,))
        i += 1
    return "\n".join(out)

def index_list(index_items):
    """The section titles the document already has, linked. A contents page, on paper."""
    if not index_items:
        return ""
    return ('<nav class="index" aria-label="Sections"><ul>%s</ul></nav>' % "".join(
        '<li><a href="#%s"><span>%s</span>%s</a></li>' % (anchor, E(label), E(t))
        for anchor, label, t in index_items))


def doc_head(h1, standfirst, version=True):
    """Full width, above the two columns. An empty standfirst renders nothing at all rather
       than an empty paragraph that still takes its margin."""
    out = ['<header class="doc-head"><h1>%s</h1>' % E(h1)]
    if standfirst:
        out.append('<p class="standfirst">%s</p>' % E(standfirst))
    if version:
        out.append('<dl class="meta"><dt>%s</dt><dd>%s</dd></dl>'
                   % (E(C.FORM["version"]), E(C.DATED)))
    out.append('</header>')
    return "\n".join(out)


def notice():
    """The standing disclaimer. Asked for on the FAQ, the terms and the connect page."""
    return '<aside class="notice" role="note"><p>%s</p></aside>' % linkify(E(C.NOTICE))

# The standfirsts come from the content module, the same place the Word edition reads them, so the
# two renderers cannot drift. They were hardcoded in both builders until a partner review pointed
# out that a sentence with two homes is a sentence that will eventually differ.
PAGES = [(k, C.TITLE[k], C.TAB[k], C.STANDFIRST[k], blocks)
         for k, blocks in (("privacy", C.PRIVACY), ("terms", C.TERMS), ("faq", C.FAQ))]

written = []
for key, h1, tab, standfirst, blocks in PAGES:
    # numbered sections index by number; the FAQ has groups instead, so it indexes those
    idx = [("s" + b[1], b[1], b[2]) for b in blocks if b[0] == "h2"]
    if not idx:
        idx = [("g-" + slug(b[1]), "", b[1]) for b in blocks if b[0] == "grp"]
    parts = [doc_head(h1, standfirst)]
    if key in ("faq", "terms"):
        parts.append(notice())
    parts.append('<div class="doc-cols">%s<div class="doc-body">%s</div></div>'
                 % (index_list(idx), render(blocks)))
    body = "\n".join(parts)
    page = head(h1, standfirst or h1, tab) + "\n" + body + "\n" + (TAIL % footer(key))
    d = os.path.join(ROOT, key)
    os.makedirs(d, exist_ok=True)
    p = os.path.join(d, "index.html")
    open(p, "w", encoding="utf-8", newline="\n").write(page)
    written.append((p, len(page)))


ICONS = {
 "LinkedIn": "M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 "
             "2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 "
             "4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 "
             "2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 "
             "13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 "
             "24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z",
 "YouTube":  "M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 "
             "0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 "
             "3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 "
             "0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 "
             "12l-6.273 3.568z",
 "X":        "M18.901 1.153h3.68l-8.04 9.19L24 22.846h-7.406l-5.8-7.584-6.638 7.584H.474l8.6-9.83L0 "
             "1.154h7.594l5.243 6.932ZM17.61 20.644h2.039L6.486 3.24H4.298Z",
}

# ONE SET OF MARKS, USED TWICE. The profile page and the connect page both carry these and they
# were about to be built twice from the same two lists. The service name lives in aria-label and
# in title so a screen reader and a pointer both get it, and the glyph is the whole control: set
# beside the words LinkedIn, YouTube and X in mono, three links read as three buttons and those
# words carry more weight than they earn.
SOCIAL_MARKS = "".join(
    '<a class="soc" href="%s" target="_blank" rel="noopener noreferrer" '
    'aria-label="%s" title="%s">'
    '<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="%s"/></svg></a>'
    % (E(url), E(name), E(name), ICONS[name])
    for name, url in C.SOCIAL if name in ICONS)

# ---------------------------------------------------------------- the connect page
# Its only prose is the FAQ's own answer to "How do I reach you?", lifted from the same content
# module rather than written again here.
FORM = """<form class="cform" id="cform" method="post" action="%(action)s" novalidate>
  <div class="cf-row">
    <label for="cf-name">%(name)s</label>
    <input id="cf-name" name="name" type="text" maxlength="120" autocomplete="name" required>
  </div>
  <div class="cf-row">
    <label for="cf-mail">%(email)s</label>
    <input id="cf-mail" name="email" type="email" maxlength="200" autocomplete="email" required>
  </div>
  <div class="cf-row">
    <label for="cf-msg">%(message)s</label>
    <textarea id="cf-msg" name="message" maxlength="4000" required></textarea>
  </div>
  <div class="cf-trap" aria-hidden="true">
    <label for="cf-url">%(trap)s</label>
    <input id="cf-url" name="website" type="text" tabindex="-1" autocomplete="off">
  </div>
  <input type="hidden" name="t0" id="cf-t0" value="">
  <div class="cf-check">
    <input id="cf-human" name="human" type="checkbox" value="1" required>
    <label for="cf-human">%(human)s</label>
  </div>
  <button class="cf-send" type="submit" id="cf-send">%(send)s</button>
  <p class="cf-out" id="cf-out" role="status" aria-live="polite"></p>
</form>""" % dict({k: E(v) for k, v in C.FORM.items()}, action=E(C.RECEIVER))

FORM_JS = """<script>
(function(){
  var f=document.getElementById('cform'), b=document.getElementById('cf-send'),
      o=document.getElementById('cf-out'), t0=document.getElementById('cf-t0');
  if(!f) return;
  t0.value = String(Date.now());
  function say(ok,msg){ o.className='cf-out on '+(ok?'ok':'bad'); o.textContent=msg; }
  f.addEventListener('submit', function(e){
    /* the browser's own validation runs first. A form marked novalidate with no check of its own
       posts empty fields, which is a defect this pattern has shipped before. */
    if(!f.reportValidity()) { e.preventDefault(); return; }
    if(!window.fetch) return;               /* no fetch: let the real POST happen */
    e.preventDefault();
    b.disabled = true; o.className='cf-out'; o.textContent='';
    var d = new FormData(f);
    fetch(f.action, {method:'POST', body:d})
      .then(function(r){ return r.json().catch(function(){ throw new Error('bad reply'); }); })
      .then(function(j){
        /* SUCCESS IS WHAT THE RECEIVER CONFIRMS, never the fact that a request completed. */
        if(j && j.ok){ say(true, '%s'); f.reset(); t0.value=String(Date.now()); }
        else { say(false, '%s'); b.disabled=false; }
      })
      .catch(function(){ say(false, '%s'); b.disabled=false; });
  });
})();
</script>"""

SENT, FAILED = C.FORM["sent"], C.FORM["failed"]

# No version row here: this page is a form, not a notice with a date in force.
# The email line sits BELOW the form, because it begins "Or" and therefore has to follow
# something. The standing notice closes the page.
# LANDSCAPE, BECAUSE IT WAS A COLUMN IN A HALL. Measured before this changed: the form was a
# 345px column pinned to the left of a 980px sheet, so more than half the page was empty and
# the email sentence wrapped to four lines with roughly 500px of nothing beside it. The form
# now takes the wider side and the ways to reach a person take the narrower one, so the sheet
# is used and there is somewhere for the eye to go once the form has been read.
#
# The email line moves in beside the marks. It begins with Or, so it still has to follow
# something, and it does: the form sits to its left and the three marks directly above it. The
# standing notice stays full width beneath both, because it qualifies the page and not a column.
CONNECT_BODY = (
    '<div class="cgrid">'
    '<div class="cgrid-form">%s%s</div>'
    '<aside class="cgrid-reach" aria-labelledby="reachh">'
    '<h2 id="reachh" class="reach-h">Connect with Ali Al Mokdad</h2>'
    '<nav class="bio-soc" aria-label="Elsewhere">%s</nav>'
    '<p class="alt">%s</p>'
    '</aside></div>'
) % (FORM, (FORM_JS % (E(SENT), E(FAILED), E(FAILED))), SOCIAL_MARKS,
     linkify(E(C.CONNECT_ALT)))

page = (head(C.TITLE["connect"], C.CONNECT_ALT, C.TAB["connect"])
        + "\n" + doc_head(C.TITLE["connect"], "", version=False)
        + "\n" + CONNECT_BODY + "\n"
        + notice()
        + "\n" + (TAIL % footer("connect")))
d = os.path.join(ROOT, "connect")
os.makedirs(d, exist_ok=True)
p = os.path.join(d, "index.html")
open(p, "w", encoding="utf-8", newline="\n").write(page)
written.append((p, len(page)))

# ---------------------------------------------------------------- /alialmokdad/
# A copy of his own about page, in this site's hand rather than that site's. His runs gold on dark
# in Cormorant; this runs blueberry on light in Source Serif with oversized mono numerals, which is
# the register's own language. Same person, visibly a different document.
#
# EVERY WORD COMES FROM C.ABOUT, which was parsed out of alialmokdad.com/about-me rather than
# retyped. The only strings this section contributes are the three social labels, which are the
# names of the three services.

A = C.ABOUT
social = SOCIAL_MARKS

expertise = "".join(
    '<li><p class="x-n">%02d</p><h3>%s</h3><p>%s</p></li>' % (i, E(label), E(detail))
    for i, (label, detail) in enumerate(A["expertise"], 1))

# A LANDSCAPE HEADER. The name, the descriptor and the three marks were stacked, so the first
# screen of a 1240px sheet was four things in a vertical pile with the width unused. They now sit
# across it: the identity on one side, the marks on the other, sharing one band. The page reads
# wide rather than tall, which is what was asked for.
#
# AN EMPTIED STRING PRINTS NOTHING. The eyebrow and the closing line were removed from the content
# rather than from the template, so both are guarded: an empty value produces no element at all,
# not an empty one holding its own margin.
eyebrow = '<p class="bio-eyebrow">%s</p>' % E(A["eyebrow"]) if A["eyebrow"].strip() else ""
closing = '<p class="bio-close">%s</p>' % E(A["closing"]) if A["closing"].strip() else ""

about_body = (
 '<header class="bio-head">'
 '<div class="bio-id">%s<h1>%s</h1><p class="bio-sub">%s</p></div>'
 '<nav class="bio-soc" aria-label="Elsewhere">%s</nav>'
 '</header>'
 '<div class="bio-cols">'
 '<section class="bio-sec"><h2>%s</h2>%s</section>'
 '<section class="bio-sec"><p class="bio-label">%s</p><h2>%s</h2>%s</section>'
 '</div>'
 '<section class="bio-sec bio-x"><h2>%s</h2><ol class="x-list">%s</ol>%s</section>'
) % (eyebrow, E(A["name"]), E(A["subtitle"]), social,
     E(A["journey_h"]), "".join("<p>%s</p>" % E(p) for p in A["journey"]),
     E(A["about_label"]), E(A["about_h"]),
     "".join("<p>%s</p>" % E(p) for p in A["about"]),
     E(A["expertise_h"]), expertise, closing)

page = (head(A["name"], A["subtitle"], "About")
        + "\n" + about_body + "\n" + (TAIL % footer("about")))
d = os.path.join(ROOT, "alialmokdad")
os.makedirs(d, exist_ok=True)
p = os.path.join(d, "index.html")
open(p, "w", encoding="utf-8", newline="\n").write(page)
written.append((p, len(page)))

for p, n in written:
    print("  %-52s %6d bytes" % (os.path.relpath(p, ROOT).replace("\\", "/"), n))
print("\nbuilt %d pages from %s" % (len(written), os.path.abspath(SRC)))

# ---------------------------------------------------------------- the SEO block
# THIS BUILD REWRITES THESE FOUR PAGES WHOLESALE, so anything another tool injected into their
# heads is destroyed by it. tools/build_seo.py maintains a marker-delimited block carrying the
# canonical, the Open Graph tags, the Twitter card and one JSON-LD object per page, across all
# thirteen real URLs on this site.
#
# LOSING IT HERE IS THE WORST KIND OF REGRESSION, and it was demonstrated rather than imagined:
# a run of this generator removed the block from all four pages while the other nine kept theirs,
# and nothing about the pages looked broken. A note telling the next person to run build_seo.py
# afterwards would have failed the same way, so this calls it instead. build_seo.py is idempotent
# and only rewrites between its own markers, so running it here is safe and running it twice is
# harmless.
seo = os.path.join(ROOT, "tools", "build_seo.py")
if os.path.exists(seo):
    import subprocess
    print("\nre-applying the SEO block, because this build just overwrote the page heads")
    r = subprocess.run([sys.executable, seo, "--write"], cwd=ROOT,
                       capture_output=True, text=True, encoding="utf-8", errors="replace")
    for line in [l for l in (r.stdout or "").splitlines() if l.strip()][-4:]:
        print("   " + line)
    if r.returncode != 0:
        print("   build_seo.py exited %d, so these four pages have NO canonical and NO share "
              "card until it runs successfully." % r.returncode)
        if r.stderr:
            print("   " + r.stderr.strip().splitlines()[-1])
else:
    print("\ntools/build_seo.py is not present, so these four pages carry no canonical and no "
          "share card while the rest of the site does.")
