# -*- coding: utf-8 -*-
"""
Builds /privacy/, /terms/, /faq/ and /connect/ from the SAME content module that produces the Word
edition of the three notices.

WHY IT IS GENERATED. These four pages carry legal statements. If the web copy and the Word copy are
written twice they will differ, and the difference will be discovered by the person the notice was
written to protect. So there is one source of words and two renderers, and the HTML is an output
rather than a document. The same reasoning, and the same arrangement, as shared/tokens.css against
the :root block in index.html.

DO NOT HAND-EDIT THE GENERATED PAGES. Edit the content module and run this again.

    py tools/build-legal.py <path-to-content.py> [repo-root]

The content module is the one used by the Word build, and EVERY string on the four pages comes out
of it. The connect form's own words live there too, in C.FORM, including the honeypot's label,
because the trap has to look like a real field to a bot and therefore needs a real one. No string
on these pages is typed into this file.
"""
import html
import os
import re
import sys
import importlib.util

SRC  = sys.argv[1] if len(sys.argv) > 1 else "content.py"
ROOT = sys.argv[2] if len(sys.argv) > 2 else os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

spec = importlib.util.spec_from_file_location("legalcontent", SRC)
C = importlib.util.module_from_spec(spec)
spec.loader.exec_module(C)

E = html.escape

# The product bar. These four pages are not products, so no entry is marked current: the page tab
# names the surface instead. The bar is here so a reader arriving from a search result has a way
# into the site rather than one link home.
PBAR = """<div class="pbar">
  <div class="wrap">
    <nav aria-label="Products">
      <a class="pbar-brand" href="../">GCC Philanthropy</a>
      <ul class="pbar-nav">
        <li><a href="../">Main page</a></li>
        <li><a href="../#/a/all">Donor Intelligence</a></li>
        <li><a href="../#/a/list">Register</a></li>
        <li><a href="../#/news">News</a></li>
        <li><a href="../toolkit/">Toolkit</a></li>
        <li><a href="../members/">Members</a></li>
      </ul>
    </nav>
  </div>
</div>"""

def masthead(tab):
    return """<header class="top">
  <div class="container">
    <p class="brandline"><a class="home" href="../">Gulf Cooperation Council <span class="abbr">(GCC)</span> Philanthropy</a></p>
    <p class="kick">United Arab Emirates &middot; Saudi Arabia &middot; Qatar &middot; Kuwait &middot; Bahrain &middot; Oman</p>
  </div>
  <span class="pagetab" aria-hidden="true">%s</span>
</header>""" % E(tab)

FOOT_LINKS = [("../faq/", "FAQ", "faq"), ("../connect/", "Connect", "connect"),
              ("../terms/", "Terms of Use", "terms"), ("../privacy/", "Privacy Policy", "privacy")]

def footer(current):
    li = []
    for href, label, key in FOOT_LINKS:
        cur = ' aria-current="page"' if key == current else ""
        li.append('      <li><a href="%s"%s>%s</a></li>' % (href, cur, E(label)))
    return ("""<footer class="sig">
  <div class="wrap">
    <ul class="sig-links">
%s
    </ul>
    <p class="sig-back"><a href="../">Gulf Cooperation Council (GCC) Philanthropy</a></p>
  </div>
</footer>""" % "\n".join(li))

def head(title, desc, tab):
    return """<!doctype html>
<!-- GENERATED by tools/build-legal.py from the same content module as the Word edition.
     DO NOT HAND-EDIT: edit the content module and run the generator again, or the web copy and
     the Word copy will say different things about the same obligation. -->
<!-- ANTI_SLOP_BRIEF
  BOLD MOVE   One white sheet on the tinted ground, the toolkit's own construction, holding a
              document read top to bottom. No cards, no accordions, no hero. A legal notice is a
              document and it is presented as one.
  TYPE        Source Serif 4 for the prose, IBM Plex Mono for the section numbers and labels.
              WEIGHTS 400 AND 600 ONLY, never lighter: a notice set in a hairline reads as
              decoration rather than a statement anyone stands behind.
  COLOUR      shared/tokens.css only. Blueberry on section numbers, links and the send button.
              Masthead navy on titles. Orange stays reserved for the page tab.
  WORDS       EVERY WORD IS GENERATED from the reviewed content module, so the page and the Word
              edition cannot disagree. That includes the headings, the form's labels, its button,
              its human check, its honeypot label and its two result lines. Nothing is typed into
              the builder.
  VERIFIABLE  The version date and the register's counts come from the same source as the Word
              edition. Nothing on these pages is estimated or restated from memory.
-->
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%s | Gulf Cooperation Council (GCC) Philanthropy</title>
<meta name="description" content="%s">
<meta name="color-scheme" content="light dark">
<link rel="icon" type="image/svg+xml" href="../gcc-emblem.svg">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="../shared/tokens.css">
<link rel="stylesheet" href="../shared/chrome.css">
<link rel="stylesheet" href="../shared/doc.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Serif+4:opsz,wght@8..60,400;8..60,600&family=IBM+Plex+Mono:wght@400;600&display=swap">
</head>
<body>
%s
%s
<main>
<div class="doc-wrap"><div class="container"><div class="sheet"><div class="doc">""" % (
        E(title), E(desc), PBAR, masthead(tab))

TAIL = """</div></div></div></div>
</main>
%s
</body>
</html>
"""

# Bare hosts in the transfer bullets and the address in the policy are the two things a reader
# reaches for. Linking them changes no word on the page.
HOST = re.compile(r"\b((?:[a-z0-9-]+\.)+(?:com|org|dev|eu|dk)(?:/[A-Za-z0-9/_.-]*)?)")
MAIL = re.compile(r"\b([a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,})\b")

def linkify(s):
    out = MAIL.sub(lambda m: '<a href="mailto:%s">%s</a>' % (m.group(1), m.group(1)), s)
    def h(m):
        u = m.group(1)
        if "@" in u or 'mailto:' in out[:m.start()][-20:]:
            return u
        return '<a href="https://%s" rel="noopener">%s</a>' % (u, u)
    parts, last = [], 0
    for m in re.finditer(r'<a [^>]*>.*?</a>', out):
        parts.append(HOST.sub(h, out[last:m.start()])); parts.append(m.group(0)); last = m.end()
    parts.append(HOST.sub(h, out[last:]))
    return "".join(parts)

def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")

def render(blocks):
    """content blocks -> html. Consecutive bullets and lettered items become one real list."""
    out, i = [], 0
    while i < len(blocks):
        b = blocks[i]; k = b[0]
        if k == "h2":
            out.append('<h2 id="s%s"><span class="n">%s</span>%s</h2>' % (b[1], E(b[1]), E(b[2])))
        elif k == "grp":
            out.append('<h2 class="grp" id="g-%s">%s</h2>' % (slug(b[1]), E(b[1])))
        elif k == "p":
            out.append("<p>%s</p>" % linkify(E(b[1])))
        elif k == "a":
            out.append("<p>%s</p>" % linkify(E(b[1])))
        elif k == "q":
            out.append("<h3>%s</h3>" % E(b[1]))
        elif k == "lead":
            out.append('<p><span class="lead">%s</span>%s</p>' % (E(b[1]), linkify(E(b[2]))))
        elif k == "kv":
            out.append('<p class="kv"><span>%s</span> <b>%s</b></p>'
                       % (E(b[1]), linkify(E(b[2]))))
        elif k == "bul":
            items = []
            while i < len(blocks) and blocks[i][0] == "bul":
                items.append("<li>%s</li>" % linkify(E(blocks[i][1]))); i += 1
            out.append("<ul>%s</ul>" % "".join(items)); continue
        elif k == "let":
            items = []
            while i < len(blocks) and blocks[i][0] == "let":
                items.append("<li>%s</li>" % linkify(E(blocks[i][2]))); i += 1
            out.append("<ol>%s</ol>" % "".join(items)); continue
        else:
            raise SystemExit("unknown block kind %r" % (k,))
        i += 1
    return "\n".join(out)

def index_list(index_items):
    """The section titles the document already has, linked. A contents page, on paper."""
    if not index_items:
        return ""
    return ('<nav class="index" aria-label="Sections"><ul>%s</ul></nav>' % "".join(
        '<li><a href="#%s"><span>%s</span>%s</a></li>' % (anchor, E(label), E(t))
        for anchor, label, t in index_items))


def doc_head(h1, standfirst, version=True):
    """Full width, above the two columns. An empty standfirst renders nothing at all rather
       than an empty paragraph that still takes its margin."""
    out = ['<header class="doc-head"><h1>%s</h1>' % E(h1)]
    if standfirst:
        out.append('<p class="standfirst">%s</p>' % E(standfirst))
    if version:
        out.append('<dl class="meta"><dt>%s</dt><dd>%s</dd></dl>'
                   % (E(C.FORM["version"]), E(C.DATED)))
    out.append('</header>')
    return "\n".join(out)


def notice():
    """The standing disclaimer. Asked for on the FAQ, the terms and the connect page."""
    return '<aside class="notice" role="note"><p>%s</p></aside>' % linkify(E(C.NOTICE))

# The standfirsts come from the content module, the same place the Word edition reads them, so the
# two renderers cannot drift. They were hardcoded in both builders until a partner review pointed
# out that a sentence with two homes is a sentence that will eventually differ.
PAGES = [(k, C.TITLE[k], C.TAB[k], C.STANDFIRST[k], blocks)
         for k, blocks in (("privacy", C.PRIVACY), ("terms", C.TERMS), ("faq", C.FAQ))]

written = []
for key, h1, tab, standfirst, blocks in PAGES:
    # numbered sections index by number; the FAQ has groups instead, so it indexes those
    idx = [("s" + b[1], b[1], b[2]) for b in blocks if b[0] == "h2"]
    if not idx:
        idx = [("g-" + slug(b[1]), "", b[1]) for b in blocks if b[0] == "grp"]
    parts = [doc_head(h1, standfirst)]
    if key in ("faq", "terms"):
        parts.append(notice())
    parts.append('<div class="doc-cols">%s<div class="doc-body">%s</div></div>'
                 % (index_list(idx), render(blocks)))
    body = "\n".join(parts)
    page = head(h1, standfirst or h1, tab) + "\n" + body + "\n" + (TAIL % footer(key))
    d = os.path.join(ROOT, key)
    os.makedirs(d, exist_ok=True)
    p = os.path.join(d, "index.html")
    open(p, "w", encoding="utf-8", newline="\n").write(page)
    written.append((p, len(page)))

# ---------------------------------------------------------------- the connect page
# Its only prose is the FAQ's own answer to "How do I reach you?", lifted from the same content
# module rather than written again here.
FORM = """<form class="cform" id="cform" method="post" action="%(action)s" novalidate>
  <div class="cf-row">
    <label for="cf-name">%(name)s</label>
    <input id="cf-name" name="name" type="text" maxlength="120" autocomplete="name" required>
  </div>
  <div class="cf-row">
    <label for="cf-mail">%(email)s</label>
    <input id="cf-mail" name="email" type="email" maxlength="200" autocomplete="email" required>
  </div>
  <div class="cf-row">
    <label for="cf-msg">%(message)s</label>
    <textarea id="cf-msg" name="message" maxlength="4000" required></textarea>
  </div>
  <div class="cf-trap" aria-hidden="true">
    <label for="cf-url">%(trap)s</label>
    <input id="cf-url" name="website" type="text" tabindex="-1" autocomplete="off">
  </div>
  <input type="hidden" name="t0" id="cf-t0" value="">
  <div class="cf-check">
    <input id="cf-human" name="human" type="checkbox" value="1" required>
    <label for="cf-human">%(human)s</label>
  </div>
  <button class="cf-send" type="submit" id="cf-send">%(send)s</button>
  <p class="cf-out" id="cf-out" role="status" aria-live="polite"></p>
</form>""" % dict({k: E(v) for k, v in C.FORM.items()}, action=E(C.RECEIVER))

FORM_JS = """<script>
(function(){
  var f=document.getElementById('cform'), b=document.getElementById('cf-send'),
      o=document.getElementById('cf-out'), t0=document.getElementById('cf-t0');
  if(!f) return;
  t0.value = String(Date.now());
  function say(ok,msg){ o.className='cf-out on '+(ok?'ok':'bad'); o.textContent=msg; }
  f.addEventListener('submit', function(e){
    /* the browser's own validation runs first. A form marked novalidate with no check of its own
       posts empty fields, which is a defect this pattern has shipped before. */
    if(!f.reportValidity()) { e.preventDefault(); return; }
    if(!window.fetch) return;               /* no fetch: let the real POST happen */
    e.preventDefault();
    b.disabled = true; o.className='cf-out'; o.textContent='';
    var d = new FormData(f);
    fetch(f.action, {method:'POST', body:d})
      .then(function(r){ return r.json().catch(function(){ throw new Error('bad reply'); }); })
      .then(function(j){
        /* SUCCESS IS WHAT THE RECEIVER CONFIRMS, never the fact that a request completed. */
        if(j && j.ok){ say(true, '%s'); f.reset(); t0.value=String(Date.now()); }
        else { say(false, '%s'); b.disabled=false; }
      })
      .catch(function(){ say(false, '%s'); b.disabled=false; });
  });
})();
</script>"""

SENT, FAILED = C.FORM["sent"], C.FORM["failed"]

# No version row here: this page is a form, not a notice with a date in force.
# The email line sits BELOW the form, because it begins "Or" and therefore has to follow
# something. The standing notice closes the page.
page = (head(C.TITLE["connect"], C.CONNECT_ALT, C.TAB["connect"])
        + "\n" + doc_head(C.TITLE["connect"], "", version=False)
        + "\n" + FORM + "\n"
        + (FORM_JS % (E(SENT), E(FAILED), E(FAILED)))
        + '\n<p class="alt">%s</p>\n' % linkify(E(C.CONNECT_ALT))
        + notice()
        + "\n" + (TAIL % footer("connect")))
d = os.path.join(ROOT, "connect")
os.makedirs(d, exist_ok=True)
p = os.path.join(d, "index.html")
open(p, "w", encoding="utf-8", newline="\n").write(page)
written.append((p, len(page)))

for p, n in written:
    print("  %-52s %6d bytes" % (os.path.relpath(p, ROOT).replace("\\", "/"), n))
print("\nbuilt %d pages from %s" % (len(written), os.path.abspath(SRC)))
